# Generated by Django 2.0.6 on 2018-07-16 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djgeojson.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KundenAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Kundennummer', models.IntegerField(null=True)),
                ('LizenzExpire', models.DateField(null=True)),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kunde',
                'verbose_name_plural': 'Kunden',
            },
        ),
        migrations.CreateModel(
            name='Messwert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(verbose_name='date measured')),
                ('Temperature', models.FloatField()),
                ('Pressure', models.FloatField()),
                ('geom', djgeojson.fields.PointField(null=True)),
            ],
            options={
                'verbose_name': 'Messwert',
                'verbose_name_plural': 'Messwerte',
            },
        ),
        migrations.CreateModel(
            name='Nutzer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=16)),
                ('KundenAdmin', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='visDat.KundenAdmin')),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nutzer',
                'verbose_name_plural': 'Nutzer',
            },
        ),
        migrations.CreateModel(
            name='Sonde',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Serial', models.CharField(max_length=16)),
                ('Date', models.DateField(verbose_name='date measured')),
                ('geom', djgeojson.fields.PointField(null=True)),
                ('picture', models.ImageField(null=True, upload_to='')),
                ('K1_temp', models.FloatField(null=True)),
                ('K2_temp', models.FloatField(null=True)),
                ('K1_pres', models.FloatField(null=True)),
                ('K2_pres', models.FloatField(null=True)),
                ('owned_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='visDat.KundenAdmin')),
            ],
            options={
                'verbose_name': 'Sonde',
                'verbose_name_plural': 'Sonden',
            },
        ),
        migrations.AddField(
            model_name='messwert',
            name='Serial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visDat.Sonde'),
        ),
    ]
