# Generated by Django 2.0.6 on 2018-07-18 06:38

from django.db import migrations, models
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('visDat', '0003_createBaseUser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messwert',
            name='Date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='messwert',
            name='geom',
            field=djgeojson.fields.PointField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sonde',
            name='Date',
            field=models.DateTimeField(null=True, verbose_name='date measured'),
        ),
    ]
